defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - id: bootstrap:cert-manager
    - id: bootstrap:nginx1
    - id: monitoring:prometheus-operator    # this will be ignored if the monitoring:prometheus-operator manifest is
                                        # excluded (i.e. with '-x monitoring:*' or '-x monitoring:prometheus-operator').

kapps:
  - id: jenkins
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/jenkins#master    #branch: jenkins-0.1.0
