defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - id: bootstrap:cert-manager
    - id: bootstrap:nginx1
    - id: monitoring:prometheus-operator    # this will be ignored if the monitoring:prometheus-operator manifest is
                                        # excluded (i.e. with '-x monitoring:*' or '-x monitoring:prometheus-operator').

kapps:
  - id: jenkins
    sources:
      - uri: https://github.com/sugarkube/kapps.git//incubator/jenkins#jenkins-0.1.0
    vars:
      cert_manager_issuer_kind: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.kind }}"
      cert_manager_issuer_name: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}"
      hostname: "{{ .kapp.id }}.{{ .cluster_hosted_zone }}"
      prometheus_hostname: "{{ .kapp.id }}-prometheus.{{ .cluster_hosted_zone }}"
      ingress_class: "nginx1"
      hosted_zone: "{{ .cluster_hosted_zone }}"
      cname_hostname: "{{ if eq .stack.provider \"aws\" }}{{ .outputs.bootstrap__nginx1.lb_hostname }}{{ end }}"
