# This manifest is for core services that are only required when running on AWS.
kapps:
  # The `kiam` chart will be installed into the `kiam` namespace, the release
  # will also be called `kiam`. The version number will be set to the version
  # extracted from `Charts.yaml` in `charts/stable/kiam/`. No `installer` block
  # is defined so defaults are used.
# the Kiam chart hasn't been tested, but it's the sort of thing you may want to install when using Kops on AWS
#  - id: kiam
#    conditions:
#    - "{{ eq .stack.provisioner \"kops\" }}"
#    sources:
#      - uri: git@github.com:sugarkube/kapps.git//incubator/kiam/#kiam-0.1.0      # you can use git URIs too
#    depends_on:   # all kapps in this manifest depend on these other kapps
#      - id: bootstrap:cert-manager

  - id: vpn
    conditions:
      - "{{ eq .stack.provider \"aws\" }}"
    sources:
      - uri: https://github.com/sugarkube/kapps.git//incubator/aws-vpn/#aws-vpn-0.1.0
    vars:
      vpc_name: "{{ .cluster_name }}"
      hostnames: "vpn.{{ .cluster_name }}"
    depends_on:
      - id: bootstrap:tiller
