defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - id: bootstrap:cert-manager
    - id: bootstrap:nginx1

kapps:
  - id: prometheus-operator
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/prometheus-operator#prometheus-operator-0.1.0
    vars:
      cert_manager_issuer_kind: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.kind }}"
      cert_manager_issuer_name: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}"
      ingress_class: "nginx1"
      prometheus_hostname: prometheus
      grafana_hostname: grafana
      alert_manager_hostname: alertmanager
      hosted_zone: "{{ .cluster_hosted_zone }}"
      cname_hostname: "{{ if eq .stack.provider \"aws\" }}{{ .outputs.bootstrap__nginx1.lb_hostname }}{{ end }}"
