defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - id: bootstrap:cert-manager
    - id: bootstrap:nginx-ext1

# A security layer. In this case it installs Keycloak which can be used as an OIDC provider
# (but this kapp so far just installs it - it doesn't configure it as yet).
kapps:
  - id: keycloak
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/keycloak#master   # todo - change to e.g. keycloak-0.1.0
