defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - id: bootstrap:cert-manager
    - id: bootstrap:nginx1

# A security layer. In this case it installs Keycloak which can be used as an OIDC provider
# (but this kapp so far just installs it - it doesn't configure it as yet).
kapps:
  - id: keycloak
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/keycloak#keycloak-0.1.0
    vars:
      cert_manager_issuer_kind: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.kind }}"
      cert_manager_issuer_name: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}"
      hostname: "{{ .kapp.id }}.{{ .cluster_hosted_zone }}"
      ingress_class: "nginx1"
      hosted_zone: "{{ .cluster_hosted_zone }}"
      cname_hostname: "{{ if eq .stack.provider \"aws\" }}{{ .outputs.bootstrap__nginx1.lb_hostname }}{{ end }}"
