# This manifest contains kapps that represent the actual products you're shipping,
# in this case web sites.

# Kapps listed under this key will be installed if they are not currently
# installed in the target cluster.
kapps:
  # This entry demonstrates how to explicitly declare values.
  #
  # Unique identifier. The same kapp can be installed multiple times provided
  # this is unique per instance. This will be the release name when using Helm.
  - id: site1
    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
      # the name of this source defaults to `wordpress` because it's the last
      # component of the path. The name can also be set explicitly as
      # illustrated below.
      - uri: git@github.com:sugarkube/kapps.git//incubator/wordpress#master
#      includeValues: false    # don't search this source for helm/terraform values
# todo - implement these paths and uncomment as an example
#    - uri: git@github.com:sugarkube/sample-project.git
#      branch: master
#      # this lets us reuse the same kapp parameterised differently per instance
#      path: examples/values/wordpress/site1/
      - id: data
        uri: git@github.com:sugarkube/sample-project.git//demo-data/wordpress/site1#master
    depends_on:
      - id: bootstrap:nginx-ext1
      - id: shared-data:site1-db
        conditions:
          - "{{ eq .stack.provider \"aws\" }}"
    vars:
      namespace: wordpress-site1      # different namespace
      hostname: "{{ .kapp.id }}.{{ .cluster_hosted_zone }}"
      hosted_zone: "{{ .cluster_hosted_zone }}"
      cname_hostname: "{{ if eq .stack.provider \"aws\" }}{{ .outputs.bootstrap__nginx_ext1.lb_hostname }}{{ end }}"
      ingress_class: "nginx-ext1"       # todo - pull this from a reference to the kapp itself
      db_host: "{{ .outputs.shared_data__site1_db.terraform.endpoint.value }}"
      db_user: "{{ .outputs.shared_data__site1_db.terraform.master_user.value }}"
      db_password: "{{ .outputs.shared_data__site1_db.terraform.master_password.value }}"
      db_name: "{{ .outputs.shared_data__site1_db.terraform.database.value }}"
      cluster_issuer: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}"

  - id: site2
    sources:
      # the implicit ID of this source is 'wordpress' because that's the last component of the path.
      # Source IDs are used for namespacing in caches, and can also be used to override settings
      # for a source from a stack config file.
      - uri: git@github.com:sugarkube/kapps.git//incubator/wordpress#master # todo change to e.g. wordpress-0.1.0
      - id: data   # the ID can be explicitly defined
        uri: git@github.com:sugarkube/sample-project.git//demo-data/wordpress/site2#master
    vars:
      hostname: "{{ .kapp.id }}.{{ .cluster_hosted_zone }}"
      hosted_zone: "{{ .cluster_hosted_zone }}"
      cname_hostname: "{{ if eq .stack.provider \"aws\" }}{{ .outputs.bootstrap__nginx_ext1.lb_hostname }}{{ end }}"
      ingress_class: "nginx-ext1"       # todo - pull this from a reference to the kapp itself
      db_host: "{{ .outputs.shared_data__site2_db.terraform.endpoint.value }}"
      db_user: "{{ .outputs.shared_data__site2_db.terraform.master_user.value }}"
      db_password: "{{ .outputs.shared_data__site2_db.terraform.master_password.value }}"
      db_name: "{{ .outputs.shared_data__site2_db.terraform.database.value }}"
      cluster_issuer: "{{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}"
    depends_on:
      - id: bootstrap:nginx-ext1
      - id: shared-data:site2-db
        conditions:
          - "{{ eq .stack.provider \"aws\" }}"
