kube_context: minikube          # todo - this should be an overrideable default for this provider

provisioner:
  # Values passed to `minikube start`. Underscores are converted to hyphens and
  # values keys prepended with two dashes. So e.g. `disk_size` is passed as `--disk-size`.
  params:
    start:        # parameters for the `minikube start` command
      bootstrapper: kubeadm
      memory: 4096
      cpus: 4
      disk_size: 50g
