defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - bootstrap:cert-manager
    - bootstrap:nginx-ingress
    - monitoring:prometheus-operator    # this will be ignored if the monitoring:prometheus-operator manifest is
                                        # excluded (i.e. with '-x monitoring:*' or '-x monitoring:prometheus-operator').

kapps:
  - id: jenkins
    state: present
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/jenkins#run-units    #branch: jenkins-0.1.0
