defaults:
  depends_on:   # all kapps in this manifest depend on these other kapps
    - bootstrap:cert-manager
    - bootstrap:nginx-ingress

kapps:
  - id: prometheus-operator
    state: present
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/prometheus-operator#master    #branch: prometheus-operator-0.1.0
      - uri: git@github.com:sugarkube/kapps.git//incubator/common-makefiles#master

  # install the standalone grafana chart instead of the subchart in the prometheus operator
  - id: grafana
    state: present
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/grafana#master    #branch: grafana-0.1.0
      - uri: git@github.com:sugarkube/kapps.git//incubator/common-makefiles#master
