# This creates infrastructure that must exist before launching a kops cluster.
# It creates an S3 bucket for Terraform remote state (not strictly necessary
# but a fiddly task that should be done before running any other kapps) and
# a hosted zone. It should be run as an initManifest so it gets executed before
# creating a cluster.
#
# If you're running on a different provider, you could either reimplement these
# kapps for your provider or create a `terraform_<provider>` directory in each
# one so a single kapp can support multiple clouds.
options:
  parallelisation: 1      # kapps in this manifest must be installed in order,
                          # so parallelism is disabled for this manifest

kapps:
  - id: terraform-remote-state
    state: present    # if 'absent' (default) the kapp won't be installed or will be deleted (todo)
    sources:
    - uri: git@github.com:sugarkube/kapps.git//incubator/terraform-remote-state#master
    - uri: git@github.com:sugarkube/kapps.git//incubator/common-makefiles#master
    templates:
    # this kapp will remove the `.tmp` extension after creating an S3 bucket
    # for remote terraform state and copying the state over to it. That way
    # subsequent runs will us the remote state directly.
  #      - source: terraform/backend.tf
  #        dest: terraform-remote-state/terraform_aws/_generated_backend.tf.tmp

  - id: hosted-zone
    state: present
    sources:
    - uri: git@github.com:sugarkube/kapps.git//incubator/hosted-zone#master
    - uri: git@github.com:sugarkube/kapps.git//incubator/common-makefiles#master
    templates:
      - source: terraform/backend.tf
        # you can use variables in source/dest paths, e.g.
        dest: hosted-zone/terraform_aws/_generated_backend-{{ .stack.region }}.tf
