# This creates infrastructure that must exist before launching a kops cluster.
# It creates an S3 bucket for Terraform remote state (not strictly necessary
# but a fiddly task that should be done before running any other kapps) and
# a hosted zone. It should be run as an initManifest so it gets executed before
# creating a cluster.
#
# If you're running on a different provider, you could either reimplement these
# kapps for your provider or create a `terraform_<provider>` directory in each
# one so a single kapp can support multiple clouds.
options:
  sequential: true      # kapps in this manifest must be installed in order. This makes each kapp depend on
                        # the preceding one without needing to explicitly define each dependency.

kapps:
  - id: terraform-bucket
    state: present    # if 'absent' (default) the kapp won't be installed or will be deleted (todo)
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/terraform-bucket#master
    templates:
    # this kapp will add a '.tf' extension after creating an S3 bucket
    # for remote terraform state and copying the state over to it. That way
    # subsequent runs will use the remote state directly.
    - source: terraform/backend.tf
      dest: terraform_aws/_generated_backend

  - id: hosted-zone
    state: present
    sources:
      - uri: git@github.com:sugarkube/kapps.git//incubator/hosted-zone#master
    templates:
      - source: terraform/backend.tf
        # you can use variables in source/dest paths, e.g.
        dest: hosted-zone/terraform_aws/_generated_backend-{{ .stack.region }}.tf
