# a higher-specced local cluster with additional settings for the monitoring stack. Values here are merged
# with, and take precedence over, values defined in `clusters/values.yaml`
provisioner:
  params:
    start:        # parameters for the `minikube start` command
      memory: 5120
      cpus: 4
      disk_size: 100g
      extra_config:       # this is a special flag that can be repeated multiple times
        - kubelet.authentication-token-webhook=true       # values required for prometheus
        - kubelet.authorization-mode=Webhook
        - scheduler.address=0.0.0.0
        - controller-manager.address=0.0.0.0
