defaults: &defaults
  provider: local
  provisioner: minikube
  profile: local
  provider_vars_dirs:   # YAML files under here will be recursively merged. Used to configure
  - ../providers/  # providers. Errors will be thrown if expected dirs don't exist.
  kapp_vars_dirs:       # The values in YAML files in these directories will be recursively merged
    - ../kapp-vars/    # into a single map/dict. The resulting values can be used to template
      # files for kapps, or kapps can declare that they need them set as
    # parameters/env vars in their `sugarkube.yaml` file.
  template_dirs:
    - ../templates/    # Source template file directories. Manifests can refer to files in these
      # directories to write templated files into kapps to parameterise them by
    # cluster/provider/profile, etc.

local-web:        # a local stack for web development
  <<: *defaults
  cluster: standard
  manifests:        # Manifests are executed by running `sugarkube kapps apply`
    # todo - support pulling these from git repos
    - uri: ../manifests/bootstrap.yaml
    - uri: ../manifests/wordpress-sites.yaml
      id: wordpress       # explicitly set the manifest ID. Will be used as a prefix to generate kapp IDs.
      overrides:
        site2:
          state: present    # explicitly enable this site we're pretending is still in dev

# todo - document it's possible to run these stacks while overriding e.g. just the cluster
# name to deploy there. Then we could have stacks for different tasks (e.g. opsy-stuff,
# ci-cd, monitoring) and devs could just deploy them to their own cluster without
# duplicating these different stacks, one per developer).
local-ops:        # local stack for ops-type work
  <<: *defaults
  cluster: large
  manifests:
    # if no protocol is given, file:// is assumed.
    - uri: ../manifests/bootstrap.yaml
    - uri: ../manifests/security.yaml
    - uri: ../manifests/ci-cd.yaml
